NUM_KEYPOINTS = 17
auto_scale_lr = dict(base_batch_size=1024)
backend_args = dict(backend='local')
base_lr = 0.008
codec = dict(
    input_size=(
        256,
        256,
    ),
    normalize=False,
    sigma=(
        12,
        12,
    ),
    simcc_split_ratio=2.0,
    type='SimCCLabel',
    use_dark=False)
custom_hooks = [
    dict(
        ema_type='ExpMomentumEMA',
        momentum=0.0002,
        priority=49,
        type='EMAHook',
        update_buffers=True),
    dict(
        switch_epoch=450,
        switch_pipeline=[
            dict(backend_args=dict(backend='local'), type='LoadImage'),
            dict(type='GetBBoxCenterScale'),
            dict(direction='horizontal', type='RandomFlip'),
            dict(type='RandomHalfBody'),
            dict(
                rotate_factor=60,
                scale_factor=[
                    0.75,
                    1.25,
                ],
                shift_factor=0.0,
                type='RandomBBoxTransform'),
            dict(input_size=(
                256,
                256,
            ), type='TopdownAffine'),
            dict(type='mmdet.YOLOXHSVRandomAug'),
            dict(
                transforms=[
                    dict(p=0.1, type='Blur'),
                    dict(p=0.1, type='MedianBlur'),
                    dict(
                        max_height=0.4,
                        max_holes=1,
                        max_width=0.4,
                        min_height=0.2,
                        min_holes=1,
                        min_width=0.2,
                        p=0.5,
                        type='CoarseDropout'),
                ],
                type='Albumentation'),
            dict(
                encoder=dict(
                    input_size=(
                        256,
                        256,
                    ),
                    normalize=False,
                    sigma=(
                        12,
                        12,
                    ),
                    simcc_split_ratio=2.0,
                    type='SimCCLabel',
                    use_dark=False),
                type='GenerateTarget'),
            dict(type='PackPoseInputs'),
        ],
        type='mmdet.PipelineSwitchHook'),
]
data_mode = 'topdown'
data_root = '/root/autodl-tmp/coco'
dataset_info = dict(
    dataset_name='coco',
    joint_weights=[
        1.0,
        1.0,
        1.0,
        1.0,
        1.0,
        1.0,
        1.0,
        1.0,
        1.0,
        1.0,
        1.0,
        1.0,
        1.0,
        1.0,
        1.0,
        1.0,
        1.0,
    ],
    keypoint_info=dict({
        0:
        dict(color=[
            255,
            0,
            0,
        ], id=0, name='nose', swap='', type='upper'),
        1:
        dict(
            color=[
                0,
                255,
                0,
            ],
            id=1,
            name='left_eye',
            swap='right_eye',
            type='upper'),
        10:
        dict(
            color=[
                0,
                128,
                128,
            ],
            id=10,
            name='right_wrist',
            swap='left_wrist',
            type='upper'),
        11:
        dict(
            color=[
                128,
                0,
                128,
            ],
            id=11,
            name='left_hip',
            swap='right_hip',
            type='lower'),
        12:
        dict(
            color=[
                64,
                0,
                0,
            ],
            id=12,
            name='right_hip',
            swap='left_hip',
            type='lower'),
        13:
        dict(
            color=[
                0,
                64,
                0,
            ],
            id=13,
            name='left_knee',
            swap='right_knee',
            type='lower'),
        14:
        dict(
            color=[
                0,
                0,
                64,
            ],
            id=14,
            name='right_knee',
            swap='left_knee',
            type='lower'),
        15:
        dict(
            color=[
                64,
                64,
                0,
            ],
            id=15,
            name='left_ankle',
            swap='right_ankle',
            type='lower'),
        16:
        dict(
            color=[
                0,
                64,
                64,
            ],
            id=16,
            name='right_ankle',
            swap='left_ankle',
            type='lower'),
        2:
        dict(
            color=[
                0,
                0,
                255,
            ],
            id=2,
            name='right_eye',
            swap='left_eye',
            type='upper'),
        3:
        dict(
            color=[
                255,
                255,
                0,
            ],
            id=3,
            name='left_ear',
            swap='right_ear',
            type='upper'),
        4:
        dict(
            color=[
                0,
                255,
                255,
            ],
            id=4,
            name='right_ear',
            swap='left_ear',
            type='upper'),
        5:
        dict(
            color=[
                255,
                0,
                255,
            ],
            id=5,
            name='left_shoulder',
            swap='right_shoulder',
            type='upper'),
        6:
        dict(
            color=[
                128,
                0,
                0,
            ],
            id=6,
            name='right_shoulder',
            swap='left_shoulder',
            type='upper'),
        7:
        dict(
            color=[
                0,
                128,
                0,
            ],
            id=7,
            name='left_elbow',
            swap='right_elbow',
            type='upper'),
        8:
        dict(
            color=[
                0,
                0,
                128,
            ],
            id=8,
            name='right_elbow',
            swap='left_elbow',
            type='upper'),
        9:
        dict(
            color=[
                128,
                128,
                0,
            ],
            id=9,
            name='left_wrist',
            swap='right_wrist',
            type='upper')
    }),
    paper_info=dict(
        author='JYUAN',
        container='OpenMMLab',
        title='Squat Keypoints Detection',
        year='2025'),
    sigmas=[
        0.025,
        0.025,
        0.025,
        0.025,
        0.025,
        0.025,
        0.025,
        0.025,
        0.025,
        0.025,
        0.025,
        0.025,
        0.025,
        0.025,
        0.025,
        0.025,
        0.025,
    ],
    skeleton_info=dict({
        0:
        dict(
            color=[
                100,
                150,
                200,
            ], id=0, link=(
                'left_ankle',
                'left_knee',
            )),
        1:
        dict(color=[
            200,
            100,
            150,
        ], id=1, link=(
            'left_knee',
            'left_hip',
        )),
        10:
        dict(
            color=[
                150,
                100,
                100,
            ],
            id=10,
            link=(
                'left_elbow',
                'left_wrist',
            )),
        11:
        dict(
            color=[
                100,
                150,
                150,
            ],
            id=11,
            link=(
                'right_elbow',
                'right_wrist',
            )),
        12:
        dict(color=[
            200,
            200,
            100,
        ], id=12, link=(
            'left_eye',
            'right_eye',
        )),
        13:
        dict(color=[
            100,
            100,
            200,
        ], id=13, link=(
            'nose',
            'left_eye',
        )),
        14:
        dict(color=[
            150,
            150,
            150,
        ], id=14, link=(
            'nose',
            'right_eye',
        )),
        15:
        dict(color=[
            200,
            150,
            150,
        ], id=15, link=(
            'left_eye',
            'left_ear',
        )),
        16:
        dict(
            color=[
                150,
                200,
                200,
            ], id=16, link=(
                'right_eye',
                'right_ear',
            )),
        17:
        dict(
            color=[
                100,
                100,
                100,
            ],
            id=17,
            link=(
                'left_ear',
                'left_shoulder',
            )),
        18:
        dict(
            color=[
                200,
                200,
                200,
            ],
            id=18,
            link=(
                'right_ear',
                'right_shoulder',
            )),
        2:
        dict(
            color=[
                150,
                120,
                100,
            ],
            id=2,
            link=(
                'right_ankle',
                'right_knee',
            )),
        3:
        dict(
            color=[
                100,
                200,
                150,
            ], id=3, link=(
                'right_knee',
                'right_hip',
            )),
        4:
        dict(color=[
            150,
            100,
            200,
        ], id=4, link=(
            'left_hip',
            'right_hip',
        )),
        5:
        dict(
            color=[
                200,
                150,
                100,
            ],
            id=5,
            link=(
                'left_shoulder',
                'left_hip',
            )),
        6:
        dict(
            color=[
                100,
                150,
                100,
            ],
            id=6,
            link=(
                'right_shoulder',
                'right_hip',
            )),
        7:
        dict(
            color=[
                150,
                200,
                150,
            ],
            id=7,
            link=(
                'left_shoulder',
                'right_shoulder',
            )),
        8:
        dict(
            color=[
                200,
                100,
                100,
            ],
            id=8,
            link=(
                'left_shoulder',
                'left_elbow',
            )),
        9:
        dict(
            color=[
                100,
                200,
                100,
            ],
            id=9,
            link=(
                'right_shoulder',
                'right_elbow',
            ))
    }))
dataset_type = 'CocoDataset'
default_hooks = dict(
    badcase=dict(
        _scope_='mmpose',
        badcase_thr=5,
        enable=False,
        metric_type='loss',
        out_dir='badcase',
        type='BadCaseAnalysisHook'),
    checkpoint=dict(
        _scope_='mmpose',
        interval=10,
        max_keep_ckpts=2,
        rule='greater',
        save_best='PCK',
        type='CheckpointHook'),
    logger=dict(_scope_='mmpose', interval=1, type='LoggerHook'),
    param_scheduler=dict(_scope_='mmpose', type='ParamSchedulerHook'),
    sampler_seed=dict(_scope_='mmpose', type='DistSamplerSeedHook'),
    timer=dict(_scope_='mmpose', type='IterTimerHook'),
    visualization=dict(
        _scope_='mmpose', enable=False, type='PoseVisualizationHook'))
default_scope = 'mmpose'
env_cfg = dict(
    cudnn_benchmark=False,
    dist_cfg=dict(backend='nccl'),
    mp_cfg=dict(mp_start_method='fork', opencv_num_threads=0))
launcher = 'none'
load_from = None
log_level = 'INFO'
log_processor = dict(
    _scope_='mmpose',
    by_epoch=True,
    num_digits=6,
    type='LogProcessor',
    window_size=50)
max_epochs = 500
model = dict(
    backbone=dict(
        _scope_='mmdet',
        act_cfg=dict(type='SiLU'),
        arch='P5',
        channel_attention=True,
        deepen_factor=0.67,
        expand_ratio=0.5,
        init_cfg=dict(
            checkpoint=
            'https://download.openmmlab.com/mmdetection/v3.0/rtmdet/cspnext_rsb_pretrain/cspnext-m_8xb256-rsb-a1-600e_in1k-ecb3bbd9.pth',
            prefix='backbone.',
            type='Pretrained'),
        norm_cfg=dict(type='SyncBN'),
        out_indices=(4, ),
        type='CSPNeXt',
        widen_factor=0.75),
    data_preprocessor=dict(
        bgr_to_rgb=True,
        mean=[
            123.675,
            116.28,
            103.53,
        ],
        std=[
            58.395,
            57.12,
            57.375,
        ],
        type='PoseDataPreprocessor'),
    head=dict(
        decoder=dict(
            input_size=(
                256,
                256,
            ),
            normalize=False,
            sigma=(
                12,
                12,
            ),
            simcc_split_ratio=2.0,
            type='SimCCLabel',
            use_dark=False),
        final_layer_kernel_size=7,
        gau_cfg=dict(
            act_fn='SiLU',
            drop_path=0.0,
            dropout_rate=0.0,
            expansion_factor=2,
            hidden_dims=256,
            pos_enc=False,
            s=128,
            use_rel_bias=False),
        in_channels=768,
        in_featuremap_size=(
            8,
            8,
        ),
        input_size=(
            256,
            256,
        ),
        loss=dict(
            beta=10.0,
            label_softmax=True,
            type='KLDiscretLoss',
            use_target_weight=True),
        out_channels=17,
        simcc_split_ratio=2.0,
        type='RTMCCHead'),
    test_cfg=dict(flip_test=True),
    type='TopdownPoseEstimator')
optim_wrapper = dict(
    optimizer=dict(lr=0.008, type='AdamW', weight_decay=0.05),
    paramwise_cfg=dict(
        bias_decay_mult=0, bypass_duplicate=True, norm_decay_mult=0),
    type='OptimWrapper')
param_scheduler = [
    dict(begin=0, by_epoch=False, end=20, start_factor=1e-05, type='LinearLR'),
    dict(
        T_max=250,
        begin=250,
        by_epoch=True,
        convert_to_iter_based=True,
        end=500,
        eta_min=0.0004,
        type='CosineAnnealingLR'),
]
randomness = dict(seed=21)
resume = False
stage2_num_epochs = 50
test_cfg = dict()
test_dataloader = dict(
    batch_size=34,
    dataset=dict(
        ann_file='annotations/val_coco.json',
        data_mode='topdown',
        data_prefix=dict(img='val/'),
        data_root='/root/autodl-tmp/coco',
        metainfo=dict(
            dataset_name='coco',
            joint_weights=[
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
            ],
            keypoint_info=dict({
                0:
                dict(
                    color=[
                        255,
                        0,
                        0,
                    ],
                    id=0,
                    name='nose',
                    swap='',
                    type='upper'),
                1:
                dict(
                    color=[
                        0,
                        255,
                        0,
                    ],
                    id=1,
                    name='left_eye',
                    swap='right_eye',
                    type='upper'),
                10:
                dict(
                    color=[
                        0,
                        128,
                        128,
                    ],
                    id=10,
                    name='right_wrist',
                    swap='left_wrist',
                    type='upper'),
                11:
                dict(
                    color=[
                        128,
                        0,
                        128,
                    ],
                    id=11,
                    name='left_hip',
                    swap='right_hip',
                    type='lower'),
                12:
                dict(
                    color=[
                        64,
                        0,
                        0,
                    ],
                    id=12,
                    name='right_hip',
                    swap='left_hip',
                    type='lower'),
                13:
                dict(
                    color=[
                        0,
                        64,
                        0,
                    ],
                    id=13,
                    name='left_knee',
                    swap='right_knee',
                    type='lower'),
                14:
                dict(
                    color=[
                        0,
                        0,
                        64,
                    ],
                    id=14,
                    name='right_knee',
                    swap='left_knee',
                    type='lower'),
                15:
                dict(
                    color=[
                        64,
                        64,
                        0,
                    ],
                    id=15,
                    name='left_ankle',
                    swap='right_ankle',
                    type='lower'),
                16:
                dict(
                    color=[
                        0,
                        64,
                        64,
                    ],
                    id=16,
                    name='right_ankle',
                    swap='left_ankle',
                    type='lower'),
                2:
                dict(
                    color=[
                        0,
                        0,
                        255,
                    ],
                    id=2,
                    name='right_eye',
                    swap='left_eye',
                    type='upper'),
                3:
                dict(
                    color=[
                        255,
                        255,
                        0,
                    ],
                    id=3,
                    name='left_ear',
                    swap='right_ear',
                    type='upper'),
                4:
                dict(
                    color=[
                        0,
                        255,
                        255,
                    ],
                    id=4,
                    name='right_ear',
                    swap='left_ear',
                    type='upper'),
                5:
                dict(
                    color=[
                        255,
                        0,
                        255,
                    ],
                    id=5,
                    name='left_shoulder',
                    swap='right_shoulder',
                    type='upper'),
                6:
                dict(
                    color=[
                        128,
                        0,
                        0,
                    ],
                    id=6,
                    name='right_shoulder',
                    swap='left_shoulder',
                    type='upper'),
                7:
                dict(
                    color=[
                        0,
                        128,
                        0,
                    ],
                    id=7,
                    name='left_elbow',
                    swap='right_elbow',
                    type='upper'),
                8:
                dict(
                    color=[
                        0,
                        0,
                        128,
                    ],
                    id=8,
                    name='right_elbow',
                    swap='left_elbow',
                    type='upper'),
                9:
                dict(
                    color=[
                        128,
                        128,
                        0,
                    ],
                    id=9,
                    name='left_wrist',
                    swap='right_wrist',
                    type='upper')
            }),
            paper_info=dict(
                author='JYUAN',
                container='OpenMMLab',
                title='Squat Keypoints Detection',
                year='2025'),
            sigmas=[
                0.025,
                0.025,
                0.025,
                0.025,
                0.025,
                0.025,
                0.025,
                0.025,
                0.025,
                0.025,
                0.025,
                0.025,
                0.025,
                0.025,
                0.025,
                0.025,
                0.025,
            ],
            skeleton_info=dict({
                0:
                dict(
                    color=[
                        100,
                        150,
                        200,
                    ],
                    id=0,
                    link=(
                        'left_ankle',
                        'left_knee',
                    )),
                1:
                dict(
                    color=[
                        200,
                        100,
                        150,
                    ],
                    id=1,
                    link=(
                        'left_knee',
                        'left_hip',
                    )),
                10:
                dict(
                    color=[
                        150,
                        100,
                        100,
                    ],
                    id=10,
                    link=(
                        'left_elbow',
                        'left_wrist',
                    )),
                11:
                dict(
                    color=[
                        100,
                        150,
                        150,
                    ],
                    id=11,
                    link=(
                        'right_elbow',
                        'right_wrist',
                    )),
                12:
                dict(
                    color=[
                        200,
                        200,
                        100,
                    ],
                    id=12,
                    link=(
                        'left_eye',
                        'right_eye',
                    )),
                13:
                dict(
                    color=[
                        100,
                        100,
                        200,
                    ],
                    id=13,
                    link=(
                        'nose',
                        'left_eye',
                    )),
                14:
                dict(
                    color=[
                        150,
                        150,
                        150,
                    ],
                    id=14,
                    link=(
                        'nose',
                        'right_eye',
                    )),
                15:
                dict(
                    color=[
                        200,
                        150,
                        150,
                    ],
                    id=15,
                    link=(
                        'left_eye',
                        'left_ear',
                    )),
                16:
                dict(
                    color=[
                        150,
                        200,
                        200,
                    ],
                    id=16,
                    link=(
                        'right_eye',
                        'right_ear',
                    )),
                17:
                dict(
                    color=[
                        100,
                        100,
                        100,
                    ],
                    id=17,
                    link=(
                        'left_ear',
                        'left_shoulder',
                    )),
                18:
                dict(
                    color=[
                        200,
                        200,
                        200,
                    ],
                    id=18,
                    link=(
                        'right_ear',
                        'right_shoulder',
                    )),
                2:
                dict(
                    color=[
                        150,
                        120,
                        100,
                    ],
                    id=2,
                    link=(
                        'right_ankle',
                        'right_knee',
                    )),
                3:
                dict(
                    color=[
                        100,
                        200,
                        150,
                    ],
                    id=3,
                    link=(
                        'right_knee',
                        'right_hip',
                    )),
                4:
                dict(
                    color=[
                        150,
                        100,
                        200,
                    ],
                    id=4,
                    link=(
                        'left_hip',
                        'right_hip',
                    )),
                5:
                dict(
                    color=[
                        200,
                        150,
                        100,
                    ],
                    id=5,
                    link=(
                        'left_shoulder',
                        'left_hip',
                    )),
                6:
                dict(
                    color=[
                        100,
                        150,
                        100,
                    ],
                    id=6,
                    link=(
                        'right_shoulder',
                        'right_hip',
                    )),
                7:
                dict(
                    color=[
                        150,
                        200,
                        150,
                    ],
                    id=7,
                    link=(
                        'left_shoulder',
                        'right_shoulder',
                    )),
                8:
                dict(
                    color=[
                        200,
                        100,
                        100,
                    ],
                    id=8,
                    link=(
                        'left_shoulder',
                        'left_elbow',
                    )),
                9:
                dict(
                    color=[
                        100,
                        200,
                        100,
                    ],
                    id=9,
                    link=(
                        'right_shoulder',
                        'right_elbow',
                    ))
            })),
        pipeline=[
            dict(backend_args=dict(backend='local'), type='LoadImage'),
            dict(type='GetBBoxCenterScale'),
            dict(input_size=(
                256,
                256,
            ), type='TopdownAffine'),
            dict(type='PackPoseInputs'),
        ],
        type='CocoDataset'),
    drop_last=False,
    num_workers=1,
    persistent_workers=True,
    sampler=dict(round_up=False, shuffle=False, type='DefaultSampler'))
test_evaluator = [
    dict(
        ann_file='/root/autodl-tmp/coco/annotations/val_coco.json',
        type='CocoMetric'),
    dict(type='PCKAccuracy'),
    dict(type='AUC'),
    dict(keypoint_indices=[
        0,
        1,
    ], norm_mode='keypoint_distance', type='NME'),
]
train_batch_size = 64
train_cfg = dict(by_epoch=True, max_epochs=500, val_interval=5)
train_dataloader = dict(
    batch_size=64,
    dataset=dict(
        ann_file='annotations/train_coco.json',
        data_mode='topdown',
        data_prefix=dict(img='train/'),
        data_root='/root/autodl-tmp/coco',
        metainfo=dict(
            dataset_name='coco',
            joint_weights=[
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
            ],
            keypoint_info=dict({
                0:
                dict(
                    color=[
                        255,
                        0,
                        0,
                    ],
                    id=0,
                    name='nose',
                    swap='',
                    type='upper'),
                1:
                dict(
                    color=[
                        0,
                        255,
                        0,
                    ],
                    id=1,
                    name='left_eye',
                    swap='right_eye',
                    type='upper'),
                10:
                dict(
                    color=[
                        0,
                        128,
                        128,
                    ],
                    id=10,
                    name='right_wrist',
                    swap='left_wrist',
                    type='upper'),
                11:
                dict(
                    color=[
                        128,
                        0,
                        128,
                    ],
                    id=11,
                    name='left_hip',
                    swap='right_hip',
                    type='lower'),
                12:
                dict(
                    color=[
                        64,
                        0,
                        0,
                    ],
                    id=12,
                    name='right_hip',
                    swap='left_hip',
                    type='lower'),
                13:
                dict(
                    color=[
                        0,
                        64,
                        0,
                    ],
                    id=13,
                    name='left_knee',
                    swap='right_knee',
                    type='lower'),
                14:
                dict(
                    color=[
                        0,
                        0,
                        64,
                    ],
                    id=14,
                    name='right_knee',
                    swap='left_knee',
                    type='lower'),
                15:
                dict(
                    color=[
                        64,
                        64,
                        0,
                    ],
                    id=15,
                    name='left_ankle',
                    swap='right_ankle',
                    type='lower'),
                16:
                dict(
                    color=[
                        0,
                        64,
                        64,
                    ],
                    id=16,
                    name='right_ankle',
                    swap='left_ankle',
                    type='lower'),
                2:
                dict(
                    color=[
                        0,
                        0,
                        255,
                    ],
                    id=2,
                    name='right_eye',
                    swap='left_eye',
                    type='upper'),
                3:
                dict(
                    color=[
                        255,
                        255,
                        0,
                    ],
                    id=3,
                    name='left_ear',
                    swap='right_ear',
                    type='upper'),
                4:
                dict(
                    color=[
                        0,
                        255,
                        255,
                    ],
                    id=4,
                    name='right_ear',
                    swap='left_ear',
                    type='upper'),
                5:
                dict(
                    color=[
                        255,
                        0,
                        255,
                    ],
                    id=5,
                    name='left_shoulder',
                    swap='right_shoulder',
                    type='upper'),
                6:
                dict(
                    color=[
                        128,
                        0,
                        0,
                    ],
                    id=6,
                    name='right_shoulder',
                    swap='left_shoulder',
                    type='upper'),
                7:
                dict(
                    color=[
                        0,
                        128,
                        0,
                    ],
                    id=7,
                    name='left_elbow',
                    swap='right_elbow',
                    type='upper'),
                8:
                dict(
                    color=[
                        0,
                        0,
                        128,
                    ],
                    id=8,
                    name='right_elbow',
                    swap='left_elbow',
                    type='upper'),
                9:
                dict(
                    color=[
                        128,
                        128,
                        0,
                    ],
                    id=9,
                    name='left_wrist',
                    swap='right_wrist',
                    type='upper')
            }),
            paper_info=dict(
                author='JYUAN',
                container='OpenMMLab',
                title='Squat Keypoints Detection',
                year='2025'),
            sigmas=[
                0.025,
                0.025,
                0.025,
                0.025,
                0.025,
                0.025,
                0.025,
                0.025,
                0.025,
                0.025,
                0.025,
                0.025,
                0.025,
                0.025,
                0.025,
                0.025,
                0.025,
            ],
            skeleton_info=dict({
                0:
                dict(
                    color=[
                        100,
                        150,
                        200,
                    ],
                    id=0,
                    link=(
                        'left_ankle',
                        'left_knee',
                    )),
                1:
                dict(
                    color=[
                        200,
                        100,
                        150,
                    ],
                    id=1,
                    link=(
                        'left_knee',
                        'left_hip',
                    )),
                10:
                dict(
                    color=[
                        150,
                        100,
                        100,
                    ],
                    id=10,
                    link=(
                        'left_elbow',
                        'left_wrist',
                    )),
                11:
                dict(
                    color=[
                        100,
                        150,
                        150,
                    ],
                    id=11,
                    link=(
                        'right_elbow',
                        'right_wrist',
                    )),
                12:
                dict(
                    color=[
                        200,
                        200,
                        100,
                    ],
                    id=12,
                    link=(
                        'left_eye',
                        'right_eye',
                    )),
                13:
                dict(
                    color=[
                        100,
                        100,
                        200,
                    ],
                    id=13,
                    link=(
                        'nose',
                        'left_eye',
                    )),
                14:
                dict(
                    color=[
                        150,
                        150,
                        150,
                    ],
                    id=14,
                    link=(
                        'nose',
                        'right_eye',
                    )),
                15:
                dict(
                    color=[
                        200,
                        150,
                        150,
                    ],
                    id=15,
                    link=(
                        'left_eye',
                        'left_ear',
                    )),
                16:
                dict(
                    color=[
                        150,
                        200,
                        200,
                    ],
                    id=16,
                    link=(
                        'right_eye',
                        'right_ear',
                    )),
                17:
                dict(
                    color=[
                        100,
                        100,
                        100,
                    ],
                    id=17,
                    link=(
                        'left_ear',
                        'left_shoulder',
                    )),
                18:
                dict(
                    color=[
                        200,
                        200,
                        200,
                    ],
                    id=18,
                    link=(
                        'right_ear',
                        'right_shoulder',
                    )),
                2:
                dict(
                    color=[
                        150,
                        120,
                        100,
                    ],
                    id=2,
                    link=(
                        'right_ankle',
                        'right_knee',
                    )),
                3:
                dict(
                    color=[
                        100,
                        200,
                        150,
                    ],
                    id=3,
                    link=(
                        'right_knee',
                        'right_hip',
                    )),
                4:
                dict(
                    color=[
                        150,
                        100,
                        200,
                    ],
                    id=4,
                    link=(
                        'left_hip',
                        'right_hip',
                    )),
                5:
                dict(
                    color=[
                        200,
                        150,
                        100,
                    ],
                    id=5,
                    link=(
                        'left_shoulder',
                        'left_hip',
                    )),
                6:
                dict(
                    color=[
                        100,
                        150,
                        100,
                    ],
                    id=6,
                    link=(
                        'right_shoulder',
                        'right_hip',
                    )),
                7:
                dict(
                    color=[
                        150,
                        200,
                        150,
                    ],
                    id=7,
                    link=(
                        'left_shoulder',
                        'right_shoulder',
                    )),
                8:
                dict(
                    color=[
                        200,
                        100,
                        100,
                    ],
                    id=8,
                    link=(
                        'left_shoulder',
                        'left_elbow',
                    )),
                9:
                dict(
                    color=[
                        100,
                        200,
                        100,
                    ],
                    id=9,
                    link=(
                        'right_shoulder',
                        'right_elbow',
                    ))
            })),
        pipeline=[
            dict(backend_args=dict(backend='local'), type='LoadImage'),
            dict(type='GetBBoxCenterScale'),
            dict(direction='horizontal', type='RandomFlip'),
            dict(
                rotate_factor=30,
                scale_factor=[
                    0.8,
                    1.2,
                ],
                type='RandomBBoxTransform'),
            dict(input_size=(
                256,
                256,
            ), type='TopdownAffine'),
            dict(type='mmdet.YOLOXHSVRandomAug'),
            dict(
                transforms=[
                    dict(p=0.5, type='ChannelShuffle'),
                    dict(p=0.5, type='CLAHE'),
                    dict(p=0.5, type='ColorJitter'),
                    dict(
                        max_height=0.3,
                        max_holes=4,
                        max_width=0.3,
                        min_height=0.2,
                        min_holes=1,
                        min_width=0.2,
                        p=0.5,
                        type='CoarseDropout'),
                ],
                type='Albumentation'),
            dict(
                encoder=dict(
                    input_size=(
                        256,
                        256,
                    ),
                    normalize=False,
                    sigma=(
                        12,
                        12,
                    ),
                    simcc_split_ratio=2.0,
                    type='SimCCLabel',
                    use_dark=False),
                type='GenerateTarget'),
            dict(type='PackPoseInputs'),
        ],
        type='CocoDataset'),
    num_workers=1,
    persistent_workers=True,
    sampler=dict(shuffle=True, type='DefaultSampler'))
train_pipeline = [
    dict(backend_args=dict(backend='local'), type='LoadImage'),
    dict(type='GetBBoxCenterScale'),
    dict(direction='horizontal', type='RandomFlip'),
    dict(
        rotate_factor=30,
        scale_factor=[
            0.8,
            1.2,
        ],
        type='RandomBBoxTransform'),
    dict(input_size=(
        256,
        256,
    ), type='TopdownAffine'),
    dict(type='mmdet.YOLOXHSVRandomAug'),
    dict(
        transforms=[
            dict(p=0.5, type='ChannelShuffle'),
            dict(p=0.5, type='CLAHE'),
            dict(p=0.5, type='ColorJitter'),
            dict(
                max_height=0.3,
                max_holes=4,
                max_width=0.3,
                min_height=0.2,
                min_holes=1,
                min_width=0.2,
                p=0.5,
                type='CoarseDropout'),
        ],
        type='Albumentation'),
    dict(
        encoder=dict(
            input_size=(
                256,
                256,
            ),
            normalize=False,
            sigma=(
                12,
                12,
            ),
            simcc_split_ratio=2.0,
            type='SimCCLabel',
            use_dark=False),
        type='GenerateTarget'),
    dict(type='PackPoseInputs'),
]
train_pipeline_stage2 = [
    dict(backend_args=dict(backend='local'), type='LoadImage'),
    dict(type='GetBBoxCenterScale'),
    dict(direction='horizontal', type='RandomFlip'),
    dict(type='RandomHalfBody'),
    dict(
        rotate_factor=60,
        scale_factor=[
            0.75,
            1.25,
        ],
        shift_factor=0.0,
        type='RandomBBoxTransform'),
    dict(input_size=(
        256,
        256,
    ), type='TopdownAffine'),
    dict(type='mmdet.YOLOXHSVRandomAug'),
    dict(
        transforms=[
            dict(p=0.1, type='Blur'),
            dict(p=0.1, type='MedianBlur'),
            dict(
                max_height=0.4,
                max_holes=1,
                max_width=0.4,
                min_height=0.2,
                min_holes=1,
                min_width=0.2,
                p=0.5,
                type='CoarseDropout'),
        ],
        type='Albumentation'),
    dict(
        encoder=dict(
            input_size=(
                256,
                256,
            ),
            normalize=False,
            sigma=(
                12,
                12,
            ),
            simcc_split_ratio=2.0,
            type='SimCCLabel',
            use_dark=False),
        type='GenerateTarget'),
    dict(type='PackPoseInputs'),
]
val_batch_size = 34
val_cfg = dict()
val_dataloader = dict(
    batch_size=34,
    dataset=dict(
        ann_file='annotations/val_coco.json',
        data_mode='topdown',
        data_prefix=dict(img='val/'),
        data_root='/root/autodl-tmp/coco',
        metainfo=dict(
            dataset_name='coco',
            joint_weights=[
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
            ],
            keypoint_info=dict({
                0:
                dict(
                    color=[
                        255,
                        0,
                        0,
                    ],
                    id=0,
                    name='nose',
                    swap='',
                    type='upper'),
                1:
                dict(
                    color=[
                        0,
                        255,
                        0,
                    ],
                    id=1,
                    name='left_eye',
                    swap='right_eye',
                    type='upper'),
                10:
                dict(
                    color=[
                        0,
                        128,
                        128,
                    ],
                    id=10,
                    name='right_wrist',
                    swap='left_wrist',
                    type='upper'),
                11:
                dict(
                    color=[
                        128,
                        0,
                        128,
                    ],
                    id=11,
                    name='left_hip',
                    swap='right_hip',
                    type='lower'),
                12:
                dict(
                    color=[
                        64,
                        0,
                        0,
                    ],
                    id=12,
                    name='right_hip',
                    swap='left_hip',
                    type='lower'),
                13:
                dict(
                    color=[
                        0,
                        64,
                        0,
                    ],
                    id=13,
                    name='left_knee',
                    swap='right_knee',
                    type='lower'),
                14:
                dict(
                    color=[
                        0,
                        0,
                        64,
                    ],
                    id=14,
                    name='right_knee',
                    swap='left_knee',
                    type='lower'),
                15:
                dict(
                    color=[
                        64,
                        64,
                        0,
                    ],
                    id=15,
                    name='left_ankle',
                    swap='right_ankle',
                    type='lower'),
                16:
                dict(
                    color=[
                        0,
                        64,
                        64,
                    ],
                    id=16,
                    name='right_ankle',
                    swap='left_ankle',
                    type='lower'),
                2:
                dict(
                    color=[
                        0,
                        0,
                        255,
                    ],
                    id=2,
                    name='right_eye',
                    swap='left_eye',
                    type='upper'),
                3:
                dict(
                    color=[
                        255,
                        255,
                        0,
                    ],
                    id=3,
                    name='left_ear',
                    swap='right_ear',
                    type='upper'),
                4:
                dict(
                    color=[
                        0,
                        255,
                        255,
                    ],
                    id=4,
                    name='right_ear',
                    swap='left_ear',
                    type='upper'),
                5:
                dict(
                    color=[
                        255,
                        0,
                        255,
                    ],
                    id=5,
                    name='left_shoulder',
                    swap='right_shoulder',
                    type='upper'),
                6:
                dict(
                    color=[
                        128,
                        0,
                        0,
                    ],
                    id=6,
                    name='right_shoulder',
                    swap='left_shoulder',
                    type='upper'),
                7:
                dict(
                    color=[
                        0,
                        128,
                        0,
                    ],
                    id=7,
                    name='left_elbow',
                    swap='right_elbow',
                    type='upper'),
                8:
                dict(
                    color=[
                        0,
                        0,
                        128,
                    ],
                    id=8,
                    name='right_elbow',
                    swap='left_elbow',
                    type='upper'),
                9:
                dict(
                    color=[
                        128,
                        128,
                        0,
                    ],
                    id=9,
                    name='left_wrist',
                    swap='right_wrist',
                    type='upper')
            }),
            paper_info=dict(
                author='JYUAN',
                container='OpenMMLab',
                title='Squat Keypoints Detection',
                year='2025'),
            sigmas=[
                0.025,
                0.025,
                0.025,
                0.025,
                0.025,
                0.025,
                0.025,
                0.025,
                0.025,
                0.025,
                0.025,
                0.025,
                0.025,
                0.025,
                0.025,
                0.025,
                0.025,
            ],
            skeleton_info=dict({
                0:
                dict(
                    color=[
                        100,
                        150,
                        200,
                    ],
                    id=0,
                    link=(
                        'left_ankle',
                        'left_knee',
                    )),
                1:
                dict(
                    color=[
                        200,
                        100,
                        150,
                    ],
                    id=1,
                    link=(
                        'left_knee',
                        'left_hip',
                    )),
                10:
                dict(
                    color=[
                        150,
                        100,
                        100,
                    ],
                    id=10,
                    link=(
                        'left_elbow',
                        'left_wrist',
                    )),
                11:
                dict(
                    color=[
                        100,
                        150,
                        150,
                    ],
                    id=11,
                    link=(
                        'right_elbow',
                        'right_wrist',
                    )),
                12:
                dict(
                    color=[
                        200,
                        200,
                        100,
                    ],
                    id=12,
                    link=(
                        'left_eye',
                        'right_eye',
                    )),
                13:
                dict(
                    color=[
                        100,
                        100,
                        200,
                    ],
                    id=13,
                    link=(
                        'nose',
                        'left_eye',
                    )),
                14:
                dict(
                    color=[
                        150,
                        150,
                        150,
                    ],
                    id=14,
                    link=(
                        'nose',
                        'right_eye',
                    )),
                15:
                dict(
                    color=[
                        200,
                        150,
                        150,
                    ],
                    id=15,
                    link=(
                        'left_eye',
                        'left_ear',
                    )),
                16:
                dict(
                    color=[
                        150,
                        200,
                        200,
                    ],
                    id=16,
                    link=(
                        'right_eye',
                        'right_ear',
                    )),
                17:
                dict(
                    color=[
                        100,
                        100,
                        100,
                    ],
                    id=17,
                    link=(
                        'left_ear',
                        'left_shoulder',
                    )),
                18:
                dict(
                    color=[
                        200,
                        200,
                        200,
                    ],
                    id=18,
                    link=(
                        'right_ear',
                        'right_shoulder',
                    )),
                2:
                dict(
                    color=[
                        150,
                        120,
                        100,
                    ],
                    id=2,
                    link=(
                        'right_ankle',
                        'right_knee',
                    )),
                3:
                dict(
                    color=[
                        100,
                        200,
                        150,
                    ],
                    id=3,
                    link=(
                        'right_knee',
                        'right_hip',
                    )),
                4:
                dict(
                    color=[
                        150,
                        100,
                        200,
                    ],
                    id=4,
                    link=(
                        'left_hip',
                        'right_hip',
                    )),
                5:
                dict(
                    color=[
                        200,
                        150,
                        100,
                    ],
                    id=5,
                    link=(
                        'left_shoulder',
                        'left_hip',
                    )),
                6:
                dict(
                    color=[
                        100,
                        150,
                        100,
                    ],
                    id=6,
                    link=(
                        'right_shoulder',
                        'right_hip',
                    )),
                7:
                dict(
                    color=[
                        150,
                        200,
                        150,
                    ],
                    id=7,
                    link=(
                        'left_shoulder',
                        'right_shoulder',
                    )),
                8:
                dict(
                    color=[
                        200,
                        100,
                        100,
                    ],
                    id=8,
                    link=(
                        'left_shoulder',
                        'left_elbow',
                    )),
                9:
                dict(
                    color=[
                        100,
                        200,
                        100,
                    ],
                    id=9,
                    link=(
                        'right_shoulder',
                        'right_elbow',
                    ))
            })),
        pipeline=[
            dict(backend_args=dict(backend='local'), type='LoadImage'),
            dict(type='GetBBoxCenterScale'),
            dict(input_size=(
                256,
                256,
            ), type='TopdownAffine'),
            dict(type='PackPoseInputs'),
        ],
        type='CocoDataset'),
    drop_last=False,
    num_workers=1,
    persistent_workers=True,
    sampler=dict(round_up=False, shuffle=False, type='DefaultSampler'))
val_evaluator = [
    dict(
        ann_file='/root/autodl-tmp/coco/annotations/val_coco.json',
        type='CocoMetric'),
    dict(type='PCKAccuracy'),
    dict(type='AUC'),
    dict(keypoint_indices=[
        0,
        1,
    ], norm_mode='keypoint_distance', type='NME'),
]
val_interval = 5
val_pipeline = [
    dict(backend_args=dict(backend='local'), type='LoadImage'),
    dict(type='GetBBoxCenterScale'),
    dict(input_size=(
        256,
        256,
    ), type='TopdownAffine'),
    dict(type='PackPoseInputs'),
]
vis_backends = [
    dict(_scope_='mmpose', type='LocalVisBackend'),
]
visualizer = dict(
    _scope_='mmpose',
    name='visualizer',
    type='PoseLocalVisualizer',
    vis_backends=[
        dict(type='LocalVisBackend'),
    ])
work_dir = './work_dirs/rtmpose-person'
